# Generated by Django 3.1.3 on 2021-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20210121_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='quartier',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
