# Generated by Django 3.1.3 on 2021-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_maison_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='ville',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
