# Generated by Django 3.1.3 on 2021-01-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_maison_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='caution',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maison',
            name='depot_initial',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='maison',
            name='disponibilite',
            field=models.DateTimeField(null=True),
        ),
    ]
