# Generated by Django 3.1.3 on 2021-01-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20210123_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='caution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='depot_initial',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
