# Generated by Django 3.1.3 on 2021-01-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20210125_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requette',
            name='prix',
            field=models.FloatField(null=True),
        ),
    ]
