# Generated by Django 3.1.3 on 2021-01-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20210125_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requette',
            name='prix',
            field=models.IntegerField(null=True),
        ),
    ]
