# Generated by Django 3.1.3 on 2021-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20210126_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='requette',
            name='nombre_chambre',
            field=models.IntegerField(null=True),
        ),
    ]
