# Generated by Django 3.1.3 on 2021-01-27 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maison',
            name='visibilite',
            field=models.BooleanField(null=True),
        ),
    ]
