# Generated by Django 3.1.3 on 2021-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_auto_20210127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='visibilite',
            field=models.BooleanField(default=False),
        ),
    ]
