# Generated by Django 3.1.3 on 2021-01-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_auto_20210127_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='photo',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('maison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.maison')),
            ],
        ),
    ]
