# Generated by Django 3.1.3 on 2021-02-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_auto_20210202_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='quartier',
            new_name='quartie',
        ),
        migrations.RenameField(
            model_name='maison',
            old_name='ville',
            new_name='vile',
        ),
    ]
