# Generated by Django 3.1.3 on 2021-02-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20210202_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='quartie',
            new_name='quartier',
        ),
        migrations.RenameField(
            model_name='maison',
            old_name='vile',
            new_name='ville',
        ),
    ]
