# Generated by Django 3.1.3 on 2021-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_auto_20210202_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='quartier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='ville',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
