# Generated by Django 3.1.3 on 2021-02-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0020_auto_20210202_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='quartier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.quartier'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.ville'),
        ),
    ]
