# Generated by Django 3.1.7 on 2021-03-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='visibilite',
        ),
    ]
