# Generated by Django 3.1.7 on 2021-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_remove_commentaire_visibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='visibilite',
            field=models.BooleanField(default=False),
        ),
    ]
