# Generated by Django 3.1.7 on 2021-03-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_commentaire_visibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='prenom',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='requette',
            name='quartier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.quartier'),
        ),
        migrations.AlterField(
            model_name='requette',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.ville'),
        ),
    ]
