# Generated by Django 3.1.7 on 2021-03-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_auto_20210306_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.categoriemaison'),
        ),
        migrations.AlterField(
            model_name='requette',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.categoriemaison'),
        ),
    ]
