# Generated by Django 3.1.7 on 2021-03-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_auto_20210306_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
